name: CI

on: [push]

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
    - name: Run all the integration tests
      run: |
        echo $(pwd)
        ls -al
        cd tests
        ./tests.sh
