name: CI

on: [push]

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run all the integration tests
      run: |
        cd tests
        ./test.sh
